# config/packages/doctrine_migrations.yaml
doctrine_migrations:
    dir_name: '%kernel.project_dir%/migrations'
    namespace: DoctrineMigrations
    table_name: migration_versions
    column_name: version
    column_length: 14
    executed_at_column_name: executed_at
    all_or_nothing: true
    check_database_platform: true
