# config/packages/translation.yaml
framework:
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['en']
        paths:
            - '%kernel.project_dir%/custom_translations'  # Ajouter des chemins supplémentaires si nécessaire
