# config/packages/validator.yaml
framework:
    validation:
        enabled: true
        enable_annotations: true
        mapping:
            paths: ['%kernel.project_dir%/config/validator/validation.yaml']
        translation_domain: validators
