# config/services.yaml
services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Services are private by default

    # Makes the App\ namespace available to the service container
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Controllers are registered as services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Add more service definitions as needed
